services:
  db:
    image: postgres:15-alpine
    container_name: jpa-db
    ports:
      - "5432:5432"
    environment:
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
       - POSTGRES_DB=bookstore-jpa
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - jpaapi-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app: 
    build: .
    container_name: jpa-api
    ports:
      - "8080:8080"
    networks:
      - jpaapi-networks
    depends_on:
      db:
        condition: service_healthy 
    
    environment:
       - SPRING_PROFILES_ACTIVE=prod
       - DB_USER=${DB_USER}
       - DB_PASSWORD=${DB_PASSWORD}

volumes:
  postgres-data:

networks:
  jpaapi-networks: